server:
    port: 8000
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
spring:
    application:
        name: cambio-service
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/cambio_service?useTimezone=true&serverTimezone=UTC
        username: root
        password: 7504
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQLDialect
    flyway:
        url: jdbc:mysql://localhost:3306/cambio_service?useTimezone=true&serverTimezone=UTC
        user: root
        password: 7504
management:
    tracing:
        sampling:
            probability: 1.0 # representa porcentagem, 1.0 representa 100%, 0.1 10%
    zipkin:
        tracing:
            endpoint: http://zipkin-server:9411/api/v2/spans
springdoc:
    api-docs:
        path: /cambio-service/v3/api-docs