version: '3.4'

services:
  zipkin-server:
    image: openzipkin/zipkin:2.24.3
    restart: always
    ports:
      - "9411:9411"
    depends_on:
      - rabbit-mq
    environment:
      RABBIT_URI: amqp://guest:guest@rabbit-mq:5672
      SPRING_RABBITMQ_HOST: rabbit-mq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit
    networks:
      - herlandio7-network
  rabbit-mq:
    image: rabbitmq:3.12.6-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - herlandio7-network
  cambio-db:
    image: mysql:8.0.33
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: 7504
      MYSQL_USER: docker
      MYSQL_PASSWORD: 7504
      MYSQL_DATABASE: cambio_service
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3308
    ports:
      - "3308:3308"
    expose:
      - 3308
    networks:
      - herlandio7-network
  book-db:
    image: mysql:8.0.33
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: 7504
      MYSQL_USER: docker
      MYSQL_PASSWORD: 7504
      MYSQL_DATABASE: book_service
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3310
    ports:
      - "3310:3310"
    expose:
      - 3310
    networks:
      - herlandio7-network
  naming-server:
    image: herlandio7/naming-server:0.0.1-SNAPSHOT
    ports:
      - "8761:8761"
    networks:
      - herlandio7-network
  cambio-service:
    image: herlandio7/cambio-service
    restart: always
    build: 
      context: .
      dockerfile: cambio-service/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://naming-server:8761/eureka
      SPRING_ZIPKIN_BASEURL: http://zipkin-server:9411/
      SPRING_DATASOURCE_URL: jdbc:mysql://cambio-db:3308/cambio_service?useSSL=false&serverTimezone=UTC&enabledTLSProtocols=TLSv1.2
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 7504
      SPRING_FLYWAY_URL: jdbc:mysql://cambio-db:3308/cambio_service?useSSL=false&serverTimezone=UTC&enabledTLSProtocols=TLSv1.2
      SPRING_FLYWAY_USER: root
      SPRING_FLYWAY_PASSWORD: 7504
      RABBIT_URI: amqp://guest:guest@rabbit-mq:5672
      SPRING_RABBITMQ_HOST: rabbit-mq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit
    ports:
      - "8000:8000"
    depends_on:
      - naming-server
      - cambio-db
      - rabbit-mq
    networks:
      - herlandio7-network
  book-service:
    image: herlandio7/book-service
    restart: always
    build: 
      context: .
      dockerfile: book-service/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://naming-server:8761/eureka
      SPRING_ZIPKIN_BASEURL: http://zipkin-server:9411/
      SPRING_DATASOURCE_URL: jdbc:mysql://book-db:3310/book_service?useSSL=false&serverTimezone=UTC&enabledTLSProtocols=TLSv1.2
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 7504
      SPRING_FLYWAY_URL: jdbc:mysql://book-db:3310/book_service?useSSL=false&serverTimezone=UTC&enabledTLSProtocols=TLSv1.2
      SPRING_FLYWAY_USER: root
      SPRING_FLYWAY_PASSWORD: 7504
      RABBIT_URI: amqp://guest:guest@rabbit-mq:5672
      SPRING_RABBITMQ_HOST: rabbit-mq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit
    ports:
      - "8100:8100"
    depends_on:
      - naming-server
      - book-db
      - rabbit-mq
    networks:
      - herlandio7-network
  api-gateway:
    image: herlandio7/api-gateway:0.0.1-SNAPSHOT
    ports:
      - 8765:8765
    networks:
      - herlandio7-network
    depends_on:
      - naming-server
      - rabbit-mq
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://naming-server:8761/eureka
      SPRING_ZIPKIN_BASEURL: http://zipkin-server:9411
      RABBIT_URI: amqp://guest:guest@rabbit-mq:5672
networks:
  herlandio7-network:
    driver: bridge