server:
    port: 8765
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
management:
    tracing:
        sampling:
            probability: 1.0 # representa porcentagem, 1.0 representa 100%, 0.1 10%
    zipkin:
        tracing:
            endpoint: http://zipkin-server:9411/api/v2/spans    
spring:
    application:
        name: api-gateway
    cloud:
        gateway:
            discovery:
                locator:
                    enabled: true
            routes:
            - id: cambio-service
              uri: lb://cambio-service
              predicates:
              - Path=/cambio-service/**
            - id: book-service
              uri: lb://book-service
              predicates:
              - Path=/book-service/**
            - id: openapi #http://localhost:8765/webjars/swagger-ui/index.html
              uri: lb://api-gateway
              predicates:
              - Path=/v3/api-docs/**
              filters:
              - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs                