server:
    port: 8100
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
resilience4j:
    bulkhead:
        instances:
            default:
                max-concurrent-calls: 10
    ratelimiter:
        instances:
            default:
                limit-for-period: 2 #limite por exemplo de tentaiva de request 2 por periodo
                limit-refresh-period: 10s #a cada 2 tentaivas aguarda 10
    retry:
        instances:
            foo-bar:
                max-attempts: 5 # 5 tentativas
                wait-duration: 1s # espera 1s a cada tentativa
                enable-exponential-backoff: true # a cade tentativa aumenta o tempo
spring:
    application:
        name: book-service
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/book_service?useTimezone=true&serverTimezone=UTC
        username: root
        password: 7504
    jackson:
        default-property-inclusion: NON_NULL
        serialization:
            fail-on-empty-beans: false
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQLDialect
    flyway:
        url: jdbc:mysql://localhost:3306/book_service?useTimezone=true&serverTimezone=UTC
        user: root
        password: 7504
management:
    tracing:
        sampling:
            probability: 1.0 # representa porcentagem, 1.0 representa 100%, 0.1 10%
    zipkin:
        tracing:
            endpoint: http://zipkin-server:9411/api/v2/spans
springdoc:
    api-docs:
        path: /book-service/v3/api-docs